### ISSUE TITLE
NO EJECUTA EN 1.16.4

### ISSUE THREAD

**Issue by d-rick** [someaddons/DrawerFPS#1]
**Describe the bug**
El juego no inicia al poner el mod debido a que: needs language provider javafml:36 or above to load. 
I have found 35.1

![image](https://user-images.githubusercontent.com/83624925/118178574-bcc22200-b3f9-11eb-8a81-c01d7eb7b23d.png)

**To Reproduce**
1. Instalo el mod
2. inicio el juego
3. y aparece el error

**Expected behavior**
poder jugar con el mod en minecraft 1.16.4

** Mod version **
drawerfps-1.8

** Logs **
[latest.log](https://github.com/someaddons/DrawerFPS/files/6474747/latest.log)

Crash Report:

[crash-2021-05-13_14.38.11-fml.txt](https://github.com/someaddons/DrawerFPS/files/6474748/crash-2021-05-13_14.38.11-fml.txt)

**Comment by someaddons** [comment]
fixed

**Comment by d-rick** [comment]
Sigue sin funcionar en 1.16.4
![drawerfps](https://user-images.githubusercontent.com/83624925/118333185-ebf79280-b4d0-11eb-8a34-99d5852d0372.PNG)

**Comment by PaintNinja** [comment]
Porque no usas MC 1.16.5? Todos los mods para 1.16.4 funcionan en 1.16.5 que yo sepa
