### ISSUE TITLE
[Bug]: Drawer render distance config doesn't function

### ISSUE THREAD

**Issue by Bidgam** [someaddons/DrawerFPS#4]
### Describe the bug you're experiencing

I set the DrawerFPS render distance to 50 and drawers stop rendering at what seems to be about 25-30 blocks away, the default render distance.

MC: 1.18.2 (The drop down below shows 1.18.1 because that was the closest choice)
Forge: 40.1.27
The latest DrawerFPS as of this post: drawerfps-1.18.2-2.4

Thanks for taking a look!

### Reproducability

N/A

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
afaik storage drawers also did add a render distance, so its probably their render distance applying
