### ISSUE TITLE
[Bug]: 1.19.2's metadata title is "Example Mod"

### ISSUE THREAD

**Issue by ColonelGerdauf** [someaddons/DrawerFPS#6]
### Describe the bug you're experiencing

This mod, when looked at via a launcher or external tool, reads as "Example Mod", when it could have read as "Drawer FPS".

This problem could be applicable to earlier versions like 1.18.2 and 1.16.5

### Reproducability

Simply have this mod saved in a 1.19.2 instance on a launcher such as Prism.
Then have the mod linked to its download platform via "check for updates".

Or, have the mod read in a list through mods like "Configured".

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

not applicable

**Comment by Nycto97** [comment]
Just use [KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs) for example to rename mods. You can make a very simple startup script like so:
```js
Platform.mods.drawerfps.name = 'DrawerFPS'
```

Sorry, the above is for 1.19.2, just noticed you're on 1.18.2. You'll need to search some [info](https://wiki.latvian.dev/) about renaming mods on that version with KubeJS.

**Comment by ColonelGerdauf** [comment]
First, no, this is indeed (originally) about 1.19.2. The reason I mentioned 1.18.2 was due to the fact that the issue is present in those versions. I did not realize until now that I had entered 1.18 in MC version in error.

Second, the point of my bug report is so that the mod gets properly listed and tagged in launchers. In that kind of situation, KubeJS would be useless, as the overriding information is stored in a kubejs config folder. And launchers avoid that in favour of reading the mod's metadata directly and having it in short-term cache.

Finally, given the diversity of situation and player knowledge/willingness to get into deep details, it is highly advisable to have the mods updated with the correct metadata information.

**Comment by Nycto97** [comment]
I get your point. Sadly, someaddon often does not fill in the mods.toml extensively, leaving a lot of fields blank or default.

If it helps for your launcher and if you do not intend to distribute your modpack, you could modify the mods.toml yourself. This is what I used to do before I started using KubeJS (with KubeJS I don't have to edit it every time a mod updates).

But I guess you know this yourself. I know people shouldn't be editing mods' files, but if the dev doesn't want to fill it in properly, maybe as a last resort you can edit it yourself.

This being said I still hope that the mods.toml files get filled in more extensively and how it should in the future.

**Comment by someaddons** [comment]
the displayname really is just for display purposes, it barely matters if it has a nice name or not. Not updating this mod since Storage drawers has the functionality in newer versions
